<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExtraFunctions" Version="2.0.0.51-Pre-release" />
    <PackageReference Include="MudBlazor" Version="9.10.0" />
    <PackageReference Include="MudBlazor.FontIcons.MaterialIcons" Version="1.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MCServer.Plugin\MCServer.Plugin.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Dialogs\NewItemDialog.razor" />
    <AdditionalFiles Include="Pages\PacketsPage.razor" />
    <AdditionalFiles Include="Pages\PlayersPage.razor" />
    <AdditionalFiles Include="Pages\PropertiesPage.razor" />
    <AdditionalFiles Include="Pages\ResourcesPage.razor" />
  </ItemGroup>

</Project>
